"""Add magnitude column

Revision ID: f2831a8e07f1
Revises: 45ea70836590
Create Date: 2024-11-14 21:55:10.329026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2831a8e07f1'
down_revision = '45ea70836590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('magnitude', sa.Float(), nullable=True))
    op.add_column('earthquakes', sa.Column('location', sa.String(), nullable=True))
    op.add_column('earthquakes', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earthquakes', 'year')
    op.drop_column('earthquakes', 'location')
    op.drop_column('earthquakes', 'magnitude')
    # ### end Alembic commands ###
